# install tfenv
tasks:
  - name: install tfenv
    init: |
      git clone https://github.com/tfutils/tfenv.git ~/.tfenv
      git --git-dir=$HOME/.tfenv/.git --work-tree=$HOME/.tfenv pull
      echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bash_profile
      source ~/.bash_profile
      tfenv install 1.2.3
      terraform init